# skills level and requirement xp for it
skills:
  # format: '15: 7500' -> 15 - level, 7500 - xp
  combat:
    1: 0
    2: 45
    3: 65
    4: 100
    5: 140
    6: 200
    7: 270
    8: 350
    9: 450
    10: 600
    11: 750
    12: 1000
    13: 1250
    14: 1500
    15: 2000
  mining:
    1: 0
    2: 45
    3: 65
    4: 100
    5: 140
    6: 200
    7: 270
    8: 350
    9: 450
    10: 600
    11: 750
    12: 1000
    13: 1250
    14: 1500
    15: 2000

# setup xp per different action
xp:
  mining:
    break_block: 1
  combat:
    hit: 1
    kill: 15

# requirement level for use item in specific action
# format: 'WOODEN_PICKAXE: 1' -> WOODEN_PICKAXE - item, 1 - level
requirements:
  mining:
    # pickaxes
    WOODEN_PICKAXE: 1
    STONE_PICKAXE: 3
    GOLDEN_PICKAXE: 5
    IRON_PICKAXE: 7
    DIAMOND_PICKAXE: 10
    NETHERITE_PICKAXE: 15
    # axes
    WOODEN_AXE: 1
    STONE_AXE: 4
    GOLDEN_AXE: 6
    IRON_AXE: 8
    DIAMOND_AXE: 11
    NETHERITE_AXE: 15
  combat:
    # swords
    WOODEN_SWORD: 1
    STONE_SWORD: 3
    GOLDEN_SWORD: 5
    IRON_SWORD: 7
    DIAMOND_SWORD: 10
    NETHERITE_SWORD: 15
    # axes
    WOODEN_AXE: 1
    STONE_AXE: 4
    GOLDEN_AXE: 6
    IRON_AXE: 8
    DIAMOND_AXE: 11
    NETHERITE_AXE: 15

do_level_up_messages: true

menus:
  skills:
    name: "Skills"
    tokens:
      slot: 22
      icon: NETHER_STAR
      name: "&bTokens"
      lore:
        - "Count: %tokens%"
    combat_skill:
      slot: 10
      icon: NETHERITE_SWORD
      name: "&3Skill: Combat"
      lore:
        - "&6Level: %level%"
        - "&6Exp: %xp%"
    mining_skill:
      slot: 16
      icon: NETHERITE_PICKAXE
      name: "&3Skill: Mining"
      lore:
        - "&6Level: %level%"
        - "&6Exp: %xp%"
  combat_menu:
    name: "Skill: combat"
    items:
      cur_level:
        slot: 10
        icon: WOODEN_SWORD
        name: "&4Current level:"
        lore:
          - "&6Level: %level%"
          - "&6Exp: %xp%"
      next_level:
        slot: 16
        icon: NETHERITE_SWORD
        name: "&4Next level:"
        lore:
          - "&6Level: %level%"
          - "&6Exp: %xp%"
  mining_menu:
    name: "Skill: mining"
    items:
      cur_level:
        slot: 10
        icon: WOODEN_PICKAXE
        name: "&4Current level:"
        lore:
          - "&6Level: %level%"
          - "&6Exp: %xp%"
      next_level:
        slot: 16
        icon: NETHERITE_PICKAXE
        name: "&4Next level:"
        lore:
          - "&6Level: %level%"
          - "&6Exp: %xp%"

messages:
  # use '%level%' to get action requirement level
  low_level: "&cThis item need %level% level!"

  level_up:
    combat: "&aYou got %level% combat level!"
    mining: "&aYou got %level% mining level!"

  error:
    no_permission: "&cYou can't do this!"